{
  "services": {
    "shard1": {
      "image": "playwright-tests",
      "container_name": "playwright-shard-1",
      "volumes": [
        "/Users/kundansuryansh/Documents/playwright-automation-framework-with-docker/blob-report/shard1:/app/blob-report"
      ],
      "command": "npm test -- --shard=1/2"
    },
    "shard2": {
      "image": "playwright-tests",
      "container_name": "playwright-shard-2",
      "volumes": [
        "/Users/kundansuryansh/Documents/playwright-automation-framework-with-docker/blob-report/shard2:/app/blob-report"
      ],
      "command": "npm test -- --shard=2/2"
    }
  }
}