const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

/**
 * Helper to execute shell commands and log output.
 */
function run(cmd) {
  console.log(`\n$ ${cmd}`);
  try {
    execSync(cmd, { stdio: "inherit" });
  } catch (err) {
    console.warn(`⚠️ Command failed: ${cmd}`);
    // We don't throw here so that merge-reports can still run even if tests fail
  }
}

// -------------------- 1. Parse Arguments --------------------
const shardArg = process.argv.find(a => a.startsWith("--shard="));
const shardCount = shardArg ? Number(shardArg.split("=")[1]) : 2; 

console.log(`🚀 Running tests with ${shardCount} shards`);

// -------------------- 2. Docker Setup --------------------
const imageName = "playwright-tests";
console.log("🐳 Building Docker image...");
run(`docker build -t ${imageName} .`);

// -------------------- 3. Clean & Prepare Report Folders --------------------
const rootBlobDir = path.join(process.cwd(), "blob-report");

// Clean existing reports to avoid merging old data with new data
if (fs.existsSync(rootBlobDir)) {
  console.log("🧹 Cleaning old blob reports...");
  fs.rmSync(rootBlobDir, { recursive: true, force: true });
}
fs.mkdirSync(rootBlobDir);

// -------------------- 4. Generate Docker Compose --------------------
console.log("🧩 Generating docker-compose.yml...");

let compose = `version: "3.9"\nservices:\n`;

for (let i = 1; i <= shardCount; i++) {
  compose += `
  shard${i}:
    image: ${imageName}
    container_name: playwright-shard-${i}
    volumes:
      - ${rootBlobDir}:/app/blob-report
    command: npx playwright test --shard=${i}/${shardCount}
`;
}

fs.writeFileSync("docker-compose.yml", compose);

// -------------------- 5. Run Shards --------------------
console.log("🚦 Starting shard containers in parallel...");
// --abort-on-container-exit is removed to ensure all shards finish 
// even if one fails early.
run("docker compose up");

// -------------------- 6. Merge Reports --------------------
console.log("📦 Merging all shard reports...");

/**
 * Playwright merge-reports expects a SINGLE directory as an argument.
 * It will scan that directory for all .zip files generated by the shards.
 */
run(`npx playwright merge-reports ./blob-report --reporter html`);

console.log("\n🎉 ✅ Shards processed!");
console.log("Consolidated HTML report available at: ./playwright-report/index.html");